### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aantipov** [aantipov/moiva#1]
# TODO List

## Regular tasks
- check for new articles and leave comments

## SEO
- [ ] alt text for graphs
- [ ] Twitter Meta tags. Check https://www.npmtrends.com/@angular/core-vs-angular-vs-react-vs-vue-vs-svelte page for insights

## Misc
- [ ] Add Social links
- [ ] Setup CSS Autoprefixer https://tailwindcss.com/docs/browser-support#vendor-prefixes
- [ ] Simplify Github API response
- [ ] Why Recoils has some old npm downloads???
- [ ] Shareable charts? (like gifs)
- [ ] Selector: Add app descriptions
- [ ] Improve Google Trends cache in UI
- [ ] Accessability/landmarks with headers/footers (try to use screenreader to interact w/ the side Accessability > VoiceOver) https://dequeuniversity.com/checklists/web/landmarks 
- [ ] Handle GraphQL errors
- [ ] Health check
- [ ] Check out chartjs plugins https://github.com/chartjs/awesome
- [ ] Categorise issues chart
- [ ] Add version date info to Sentry
- [ ] TypeScript support for Google Trends https://github.com/pat310/google-trends-api/issues/148

## Bugs
- [ ] Handle SEO Description for packages with badges like p5
- [ ] NPM Search can't find blitz

## Styling
- [ ] Npm Downloads - start w/ 0
- [ ] show formatted numbers in tooltip
- [ ] Loading Indicator - first time page load
- [ ] Loading Indicator - additional library load
- [ ] Show moving vertical line in Line charts
- [ ] Dark theme

## PROMO
- [ ] habrahabr
- [ ] look for similar articles-questions and answer

## Dev
- [ ] Tailwaind autosuggest in Vim
- [ ] Github Desktop Client

## Lighthouse Incognito Mobile
- [ ] Performance 65

## New Charts
- [ ] CDN stats
- [ ] BestOfJS
- [ ] Github: used by repos
- [x] Github: releases
- [ ] Github: new issues created graph
- [x] Github: contributors
- [ ] Twitter
- [ ] StackOverflow Trends https://insights.stackoverflow.com/trends?tags=jquery%2Cangularjs%2Cangular%2Creactjs%2Cvue.js
- [ ] Vacancies Indeed.com https://dev.to/techmagic/react-vs-angular-vs-vue-js-what-is-the-best-choice-in-2021-1mgj
- [ ] Salaries Indeed.com
- [ ] Frameworks usage https://w3techs.com/technologies/comparison/js-react,js-vuejs
- [ ] Github: aggregation of issues/prs by labels like `bug`, `feature`, `documentation`
- [ ] Github: How many open issues (bug) still open after 1 year
- [ ] Github: documentation issues
- [ ] Number of direct dependencies
- [ ] Licenses
- [ ] Use SNYK https://snyk.io/advisor/npm-package/chartjs-adapter-date-fns
- [ ] Chrome Extensions stats https://twitter.com/rauchg/status/1345178660140064768 https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi https://chrome-stats.com/

## Suggestions
- [ ] show in sidebar top trending JS framework by day, week , month and year.
- [x] alternatives autosuggestion
- [x] Stars chart should be in the top
- [x] Number of contributors
- [ ] issues, issues resolved ratio, date created, size, commits/PRs trends (how actively does a project grow, it's actually missing from npmtrends),
- [x] use the colors you assigned to search results consistently.
- [ ] Bundlephobia shows some useful metrics - Is it tree-shakeable? side-effect free? how many dependencies?
- [x] I also look at what languages are in the codebase, 
- [ ] and whether there are tests.
- [ ] Very cool! If you want to add in State of JS data in there we also have a public GraphQL API: graphiql.stateofjs.com/
- [ ] https://npmcompare.com/
- [x] commit frequency
- [x] put hold under assess in the tech radar chart.
- [x]  issues resolved ratio
- [ ] it would be interesting to have data on how many issues are closed vs. resolved, how long they remain open, "dead" issues, maybe correct for reasons given and/or spam to whatever extent that's possible....
- [ ] useful to incorporate a repo health indication, time since last merged PR and/or the proportion of contributions by each contributor to help select projects that are active and unlikely to become inactive if a single maintainer loses interest.
- [ ] showing if a library has built in TypeScript definitions, DefinitelyTyped definitions, or no definitions would be super helpful. Check how Openbase implemented it
- [ ] Is Archived?
- [ ] Search for and analyze Github repos
- [ ] Close button click animate
- [ ] Hide Autosuggest window right after selecting
- [ ] tooltips for all icons as in https://bestofjs.org/projects?sort=daily
- [ ] В графиках по годам 2021 лучше не показывать. Данные еще не набрались на этот год, поэтому все линии ведут в бездну, хотя на самом деле это не так
- [ ] Bundle size. А слона-то тут и не заметили. У реакта основная часть кода находится в пакете react-dom, его тоже нужно учесть
- [ ] I think Contributors per year and Releases per year, could be monthly or quarterly as it's more granular and yearly change doesn't say much for libraries that are only there for 1-2 years. I need to give it another thought, might be it makes sense to change it the way you suggest
- [ ]  - Also the history-back makes the url change but doesn't get reflected in the page Yes, I know about that problem, haven't had time yet to fix it - there were more important things to implement.
- [ ] A "clear all" button would be nice Agree. It'll be there soon.
- [ ] maybe “trendiness” is a nice metric. Could be based on the amount of stars it receives in a given month.
- [ ] Why Rome  https://www.npmjs.com/package/rome isnt linked to Github https://github.com/rome/tools

##  Vulnerabilities Proper Implementation
https://ossindex.sonatype.org/
https://www.thoughtworks.com/radar/tools/oss-index
https://github.com/sonatype-nexus-community/auditjs
https://www.npmjs.com/advisories
https://www.thoughtworks.com/radar/tools/nsp
https://nvd.nist.gov/vuln-metrics/cvss
JSDelivr uses Snyk to show vulnerabilities info https://www.jsdelivr.com/package/npm/vue
Incorparate a badge with health stats https://snyk.io/advisor/npm-package/react
https://support.snyk.io/hc/en-us/articles/360003997277-Badge-Support-for-Repositories
https://snyk.io/blog/instant-security-information-with-the-snyk-security-badge/
